quarkus:
  log:
    level: INFO
    category:
      "com.redhat.demo":
        level: DEBUG
  hibernate-orm:
    log:
      sql: true
  flyway:
    migrate-at-start: true
    locations: db/migration,db/testdata